# from retrieval.pre_LLM import ret_chunks  # Passing query and INP(Type) to pre_LLM.py for retrieval 
import json
import os
from pathlib import Path
from dotenv import load_dotenv
from groq import Groq

# from retrieval.i_retriever_second import TOC_Overview  # Function to get TOC overview from LLM

BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Importing Table of content generated by LLM from TOC_gen_LLM.py
with open(BASE_DIR/ "Backend/docs/TOC_from_llm/TOC_from_llm_1.json", "r", encoding="utf-8") as f:
    TOC_from_llm=json.load(f)
# TOC for LLM reference to extract section or chapter names from the query and decide which retrieval operation to trigger
TOC_for_LLM=json.dumps(TOC_from_llm, indent=4)


load_dotenv(BASE_DIR / ".env")
api_key = os.getenv("GROQ_API_KEY")

if not api_key:
    raise ValueError("GROQ_API_KEY not found")

client = Groq(api_key=api_key, base_url="https://api.groq.com")

# Based on the query, determine the appropriate retrieval method (INP)
def determine_retrieval_method(query):
   

    router_prompt = f"""
    You are an intelligent Retrieval Router for a RAG-based AI Teacher. Your ONLY task is to analyze the user's query and output a single, valid JSON object mapping the query to the correct operation.

    USER QUERY:
    {query}

    AVAILABLE TABLE OF CONTENTS (TOC):
    {TOC_for_LLM}

    ---

    ### OPERATIONS & TRIGGER CRITERIA

    1. hybrid_search
    - Trigger when the user asks only about a SPECIFIC piece of info, concept, definition, explanation, example, comparison, or factual question(strictly).
    - Note: If a user mentions a chapter/section but only asks about a specific sub-topic within it, you MUST use hybrid_search.
    - Add chapter and section names in the JSON output if the user explicitly mentions them in the query. If not mentioned, set them to null.

    2. metadata_filtering
    - Trigger when the user asks/ mentions chapter/ section name in the query verify this using attached TOC content. Eg: if user asks like "Explain the Making of Nationalism in Europe properly", you MUST use metadata_filtering because here you will find chapter/ section name in the query.
    - Trigger when the user wants to learn, summarize, or retrieve the COMPLETE content of an entire chapter or section.
    - Keywords indicating complete scope: "teach me the section", "explain the entire chapter", "walk me through the whole section", "complete summary".
    - The chapter/section name MUST match the provided TOC.
    - Add chapter and section names in the JSON output if the user explicitly mentions them in the query. If not mentioned, set them to null.
    - Trigger metadata_filtering even if the user mentions a chapter/section name in the query. In such cases, metadata_filtering takes precedence over hybrid_search.
    
    3. TOC_Overview
    - Trigger when the user asks only strictly about the Table of Contents, syllabus structure, covered topics, chapters, chapter page number or sections available in the book.

    4. Student_Progress_Tracking
    - Trigger when the user asks about their own learning progress, history, or concepts already studied.

    5. Student_performance_Analysis
    - Trigger when the user asks to analyze their strengths, weaknesses, learning gaps, mistakes, or performance trends.

    6. Important_Question_Generation
    - Trigger when the user asks for practice questions, exam preparation questions, or key study questions.
    - SPECIAL TEST/QUIZ RULE: If the user explicitly asks to TAKE A TEST, QUIZ, or EXAM on a chapter or section, trigger this operation and set "Test_Quiz": true. Otherwise, "Test_Quiz" must be false.
    
    7. clarification
        Trigger when the student's question is:
        - Analyse the user query carefully and determine if it is:
        - outside the educational scope of the current request
        - unclear enough that the teacher should ask the student to clarify
        - reply for greetings, small talk
        - This operation means RESUME the existing teaching state.
        - also trigger if user ask just like i have doubt, clarify without mentioning remaining .
        Dont trigger when the students's ask:
        - When student include chapter name, or subsection name in their query(identify chapter, subsection names from TOC)
        - verify query clearly with TOC and then make decision. If you find chapter, subsection name in the student question dont trigger this.
        Examples:
        - "What are you doing?", "Who are you?", "Tell me something funny", "What is the weather?", "Can you help me?", "I don't understand" (when no specific concept is mentioned), "What?", "Huh?", "Can you explain?" (without specifying what), "What does this mean?" (without enough context)
    

    ### ROUTING PRIORITY (Strict Order)
    1. Clarification
    2. SPECIFIC TOPIC/CONCEPT SCOPE → hybrid_search
    3. COMPLETE CHAPTER/SECTION SCOPE → metadata_filtering
    4. TEST/QUIZ → Important_Question_Generation ("Test_Quiz": true)
    5. STUDENT PERFORMANCE → Student_performance_Analysis
    6. STUDENT PROGRESS → Student_Progress_Tracking
    7. TOC STRUCTURE → TOC_Overview
    
    #### ARGUMENTS
    Return exactly these two keys in Argument: - query: Return the user's original query unchanged. - Optimised_query: Rewrite the query using the exact chapter, section, or subsection names from the provided TOC. 
    Rules: 1. Use the TOC as the only source for naming/normalization. 2. Correct spelling, variations, and informal references to match the TOC. 3. Keep the Optimised_query concise and TOC-specific. 4. If retrieval_method is "metadata_filtering" and the user mentions both a chapter and a section/subsection, return ONLY the relevant subsection/section name in Optimised_query. 5. Do not invent chapter or section names that are not present in the TOC. 
    Example: User: "Teach me What is a Nation? section from The Nationalism in Europe chapter." retrieval_method: "metadata_filtering" query: "Teach me What is a Nation? section from The Nationalism in Europe chapter." Optimised_query: "What is a Nation?"

    ---

    ### OUTPUT RULES & SPECIFICATION
    - Return ONLY valid raw JSON. Do NOT wrap it in markdown code blocks. No explanations.
    - In argument return Optimised_query based on the TOC attached(TOC specific). Optimising query is very important and this is my first priority.
    - Optimise query properly with common sense based on TOC tagged above.
    - Set irrelevant arguments to null.
    - "Test_Quiz" must be a boolean (true/false), never a string.

    JSON Schema:
    {{
        "trigger": ...,
        "arguments": {{
            "query": "{query}",
            "Optimised_query": str,
            "Test_Quiz": false
            
        }}
    }}
    """

    try:
        response = client.chat.completions.create(
            model="openai/gpt-oss-20b",
            messages=[
                {
                    "role": "system",
                    "content": "You are an intelligent Retrieval Router for a RAG-based AI Teacher. Your ONLY task is to analyze the user's query and output a single, valid JSON object mapping the query to the correct operation based on the instructions provided by the user."
                },
                {
                    "role": "user",
                    "content": router_prompt
                }
                
            ],
            reasoning_effort="low",
            include_reasoning=False,
            max_completion_tokens=1024
        )
        LLM_Response=response.choices[0].message.content
        return LLM_Response
        # print(f"\n Got Response from LLM Query modifier: =====> {LLM_Response}", LLM_Response)
        
    except Exception as e:
        return json.dumps({"error": str(e)})

if __name__=="__main__":
    # Pass query and INP to pre_LLM.py for retrieval
    # Query
    query="generate Important_Question_Generation from the Nationalism chapter"
    print("\n\n LLM Respone:", determine_retrieval_method(query))

# if INP in["hybrid_search", "metadata_filtering"]:
#     ret_chunks(query, INP=INP)  

# else:

#     """ calling Fn that connected to: Important_Question_Generation ("Test_Quiz": true),
#         Student_performance_Analysis,
#         Student_Progress_Tracking system, 
#         ====Not implemented yet.===="""
    
#     # TOC_Overview retrieval.
#     if INP == "TOC_Overview":
#         TOC_Overview=TOC_Overview(query)  # Code to generate overview of TOC is in retriever_second.py file and saves in docs/Final_LLM_responses/TOC_Overview_from_LLM.txt.
        
    

    


