import re


def clean_markdown(text: str) -> str:
    """
    Clean Markdown generated by PyMuPDF4LLM.

    Removes extraction artifacts while preserving normal
    textbook content.
    """

    # 1. Normalize line endings
    text = text.replace("\r\n", "\n")
    text = text.replace("\r", "\n")

    # 2. Remove complete PyMuPDF4LLM picture-text blocks
    #    Removes:
    #    <!-- Start of picture text -->
    #    ...
    #    <!-- End of picture text -->
    text = re.sub(
        r"<!--\s*Start of picture text\s*-->.*?<!--\s*End of picture text\s*-->",
        "",
        text,
        flags=re.IGNORECASE | re.DOTALL
    )

    # 3. Remove <mark> while preserving its content
    #    **<mark>Activity</mark>**
    #    ↓
    #    **Activity**
    text = re.sub(
        r"<mark>(.*?)</mark>",
        r"\1",
        text,
        flags=re.DOTALL | re.IGNORECASE
    )

    # 4. Remove <br> tags
    text = re.sub(
        r"<br\s*/?>",
        " ",
        text,
        flags=re.IGNORECASE
    )

    # 5. Remove excessive spaces/tabs
    text = re.sub(r"[ \t]+", " ", text)

    # 6. Remove spaces at beginning/end of lines
    text = "\n".join(
        line.strip()
        for line in text.splitlines()
    )

    # 7. Normalize excessive blank lines
    text = re.sub(r"\n{3,}", "\n\n", text)

    return text.strip()


def clean_heading_text(text: str) -> str:
    """
    Remove Markdown formatting from heading text
    while preserving the actual heading content.
    """

    # Remove <mark>
    text = re.sub(
        r"<mark>(.*?)</mark>",
        r"\1",
        text,
        flags=re.DOTALL | re.IGNORECASE
    )

    # Remove bold/italic markers
    text = text.replace("**", "")
    text = text.replace("__", "")
    text = text.replace("*", "_")

    # Remove inline code markers
    text = text.replace("`", "")

    return text.strip()


def normalize_headings(text: str) -> str:
    """
    Normalize Markdown heading formatting.
    """

    lines = text.splitlines()
    normalized = []

    for line in lines:

        match = re.match(
            r"^(#{1,6})\s+(.*)$",
            line
        )

        if not match:
            normalized.append(line)
            continue

        hashes = match.group(1)
        heading_text = match.group(2)

        heading_text = clean_heading_text(
            heading_text
        )

        normalized.append(
            f"{hashes} {heading_text}"
        )

    return "\n".join(normalized)


def normalize_heading_levels(text: str) -> str:
    """
    Normalize heading levels.

    Prevents jumps such as:
        ## → #####

    by limiting an increase to one level.
    """

    lines = text.splitlines()
    normalized = []

    previous_level = 0

    for line in lines:

        match = re.match(
            r"^(#{1,6})\s+(.*)$",
            line
        )

        if not match:
            normalized.append(line)
            continue

        level = len(match.group(1))
        heading_text = match.group(2)

        if previous_level == 0:
            new_level = level

        elif level > previous_level + 1:
            new_level = previous_level + 1

        else:
            new_level = level

        new_level = min(new_level, 6)

        normalized.append(
            f"{'#' * new_level} {heading_text}"
        )

        previous_level = new_level

    return "\n".join(normalized)


def clean_and_normalize_markdown(text: str) -> str:
    """
    Complete Markdown cleaning pipeline.

    1. Remove extraction artifacts
    2. Remove picture-text OCR blocks
    3. Normalize HTML tags
    4. Clean heading formatting
    5. Normalize heading levels
    """

    text = clean_markdown(text)

    text = normalize_headings(text)

    text = normalize_heading_levels(text)

    return text.strip()