import re


def clean_markdown(text: str) -> str:
    """
    Clean Markdown generated by PyMuPDF4LLM.
    
    Does not intentionally change textbook content.
    It mainly removes extraction artifacts and normalizes formatting.
    """
    
    # ---------------------------------------------------------
    # 1. Normalize line endings
    # ---------------------------------------------------------
    text = text.replace("\r\n", "\n")
    text = text.replace("\r", "\n")
    
    # ---------------------------------------------------------
    # 2. Remove HTML-style picture markers
    # ---------------------------------------------------------
    text = re.sub(
        r"<!--\s*Start of picture text\s*-->",
        "",
        text,
        flags=re.IGNORECASE
    )
    
    text = re.sub(
        r"<!--\s*End of picture text\s*-->",
        "",
        text,
        flags=re.IGNORECASE
    )
    
    # ---------------------------------------------------------
    # 3. Remove <mark> while preserving its content
    #
    # **<mark>Activity</mark>**
    #       ↓
    # **Activity**
    # ---------------------------------------------------------
    text = re.sub(r"<mark>(.*?)</mark>", r"\1", text, flags=re.DOTALL)
    
    # ---------------------------------------------------------
    # 4. Remove excessive spaces
    # ---------------------------------------------------------
    text = re.sub(r"[ \t]+", " ", text)
    
    # ---------------------------------------------------------
    # 5. Remove spaces at beginning/end of lines
    # ---------------------------------------------------------
    text = "\n".join(
        line.strip()
        for line in text.splitlines()
    )
    
    # ---------------------------------------------------------
    # 6. Normalize excessive blank lines
    # ---------------------------------------------------------
    text = re.sub(r"\n{3,}", "\n\n", text)
    
    return text.strip()


def clean_heading_text(text: str) -> str:
    """
    Remove Markdown formatting from heading text
    while preserving the actual heading content.
    """
    
    # Remove <mark>
    text = re.sub(r"<mark>(.*?)</mark>", r"\1", text)
    
    # Remove bold/italic markers
    text = text.replace("**", "")
    text = text.replace("__", "")
    text = text.replace("*", "")
    text = text.replace("_", "")
    
    # Remove inline code markers
    text = text.replace("`", "")
    
    return text.strip()


def normalize_headings(text: str) -> str:
    """
    Clean up heading formatting (remove **_text_**, <mark>, etc.)
    """
    
    lines = text.splitlines()
    normalized = []
    
    for line in lines:
        
        # Match Markdown headings
        match = re.match(r"^(#{1,6})\s+(.*)$", line)
        
        if not match:
            normalized.append(line)
            continue
        
        hashes = match.group(1)
        heading_text = match.group(2)
        
        # Clean up the heading text
        heading_text = clean_heading_text(heading_text)
        
        normalized.append(
            f"{hashes} {heading_text}"
        )
    
    return "\n".join(normalized)


def normalize_heading_levels(text: str) -> str:
    """
    Normalize heading levels - prevent jumps like ## -> #####
    
    Rules:
    - First heading stays at its level
    - Heading levels can only increase by 1
    - So ## -> ##### becomes ## -> ###
    """
    
    lines = text.splitlines()
    normalized = []
    
    previous_level = 0
    
    for line in lines:
        
        match = re.match(r"^(#{1,6})\s+(.*)$", line)
        
        if not match:
            normalized.append(line)
            continue
        
        level = len(match.group(1))
        heading_text = match.group(2)
        
        # First heading - preserve its level
        if previous_level == 0:
            new_level = level
        
        # Prevent jumps like ## -> #####
        elif level > previous_level + 1:
            new_level = previous_level + 1
        
        else:
            new_level = level
        
        # Don't exceed 6 levels
        if new_level > 6:
            new_level = 6
        
        normalized.append(
            f"{'#' * new_level} {heading_text}"
        )
        
        previous_level = new_level
    
    return "\n".join(normalized)


def clean_and_normalize_markdown(text: str) -> str:
    """
    Full pipeline:
    1. Clean artifacts and formatting
    2. Normalize heading text formatting
    3. Normalize heading levels
    """
    
    # Step 1: Basic cleaning
    text = clean_markdown(text)
    
    # Step 2: Clean heading formatting
    text = normalize_headings(text)
    
    # Step 3: Fix heading level jumps
    text = normalize_heading_levels(text)
    
    return text


# Main execution: Read, clean, and save
if __name__ == "__main__":
    def clean_and_normalize_markdown(raw_markdown):
        print("Cleaning and normalizing markdown...")
        cleaned_markdown = clean_and_normalize_markdown(raw_markdown)
        return cleaned_markdown
        
