from retrieval.pre_LLM import ret_chunks  # Passing query and INP(Type) to pre_LLM.py for retrieval 
import json
import os
from pathlib import Path
from dotenv import load_dotenv
from groq import Groq
from retrieval.retriever_second import TOC_Overview  # Function to get TOC overview from LLM


# Importing Table of content generated by LLM from TOC_gen_LLM.py
with open("docs/TOC_from_llm/TOC_from_llm_1.json", "r", encoding="utf-8") as f:
    TOC_from_llm=json.load(f)
# TOC for LLM reference to extract section or chapter names from the query and decide which retrieval operation to trigger
TOC_for_LLM=json.dumps(TOC_from_llm, indent=4)

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")
api_key = os.getenv("GROQ_API_KEY")

if not api_key:
    raise ValueError("GROQ_API_KEY not found")

client = Groq(api_key=api_key)

# Based on the query, determine the appropriate retrieval method (INP)
def determine_retrieval_method(query):
   

    router_prompt = f"""
    You are an intelligent Retrieval Router for a RAG-based AI Teacher. Your ONLY task is to analyze the user's query and output a single, valid JSON object mapping the query to the correct operation.

    USER QUERY:
    {query}

    AVAILABLE TABLE OF CONTENTS (TOC):
    {TOC_for_LLM}

    ---

    ### OPERATIONS & TRIGGER CRITERIA

    1. hybrid_search
    - Trigger when the user asks about a SPECIFIC piece of info, concept, definition, explanation, example, comparison, or factual question.
    - Note: If a user mentions a chapter/section but only asks about a specific sub-topic within it, you MUST use hybrid_search.
    - Add chapter and section names in the JSON output if the user explicitly mentions them in the query. If not mentioned, set them to null.

    2. metadata_filtering
    - Trigger when the user asks/ mentions chapter/ section name in the query. Eg: if user asks like "Explain the Making of Nationalism in Europe properly", you MUST use metadata_filtering because here you will find chapter/ section name in the query.
    - Trigger when the user wants to learn, summarize, or retrieve the COMPLETE content of an entire chapter or section.
    - Keywords indicating complete scope: "teach me the section", "explain the entire chapter", "walk me through the whole section", "complete summary".
    - The chapter/section name MUST match the provided TOC.
    - Add chapter and section names in the JSON output if the user explicitly mentions them in the query. If not mentioned, set them to null.
    - Trigger metadata_filtering even if the user mentions a chapter/section name in the query. In such cases, metadata_filtering takes precedence over hybrid_search.
    3. TOC_Overview
    - Trigger when the user asks about the Table of Contents, syllabus structure, covered topics, chapters, or sections available in the book.

    4. Student_Progress_Tracking
    - Trigger when the user asks about their own learning progress, history, or concepts already studied.

    5. Student_performance_Analysis
    - Trigger when the user asks to analyze their strengths, weaknesses, learning gaps, mistakes, or performance trends.

    6. Important_Question_Generation
    - Trigger when the user asks for practice questions, exam preparation questions, or key study questions.
    - SPECIAL TEST/QUIZ RULE: If the user explicitly asks to TAKE A TEST, QUIZ, or EXAM on a chapter or section, trigger this operation and set "Test_Quiz": true. Otherwise, "Test_Quiz" must be false.

    ---

    ### ROUTING PRIORITY (Strict Order)
    1. SPECIFIC TOPIC/CONCEPT SCOPE → hybrid_search
    2. COMPLETE CHAPTER/SECTION SCOPE → metadata_filtering
    3. TEST/QUIZ → Important_Question_Generation ("Test_Quiz": true)
    4. STUDENT PERFORMANCE → Student_performance_Analysis
    5. STUDENT PROGRESS → Student_Progress_Tracking
    6. TOC STRUCTURE → TOC_Overview
   
    

    ---

    ### OUTPUT RULES & SPECIFICATION
    - Return ONLY valid raw JSON. Do NOT wrap it in markdown code blocks. No explanations.
    - Match "section" and "chapter" parameters EXACTLY against the provided TOC. Do not invent names.
    - Set irrelevant arguments to null.
    - "Test_Quiz" must be a boolean (true/false), never a string.

    JSON Schema:
    {{
        "trigger": ...,
        "arguments": {{
            "query": "string or null",
            "section": "exact TOC string or null",
            "chapter": "exact TOC string or null",
            "Test_Quiz": false
        }}
    }}
    """

    try:
        response = client.chat.completions.create(
            model="openai/gpt-oss-20b",
            messages=[
                {
                    "role": "system",
                    "content": "You are an intelligent Retrieval Router for a RAG-based AI Teacher. Your ONLY task is to analyze the user's query and output a single, valid JSON object mapping the query to the correct operation based on the instructions provided by the user."
                },
                {
                    "role": "user",
                    "content": router_prompt
                }
                
            ],
            reasoning_effort="low",
            include_reasoning=False,
            max_completion_tokens=1024
        )
        LLM_Response=response.choices[0].message.content
        return LLM_Response
        print("\n Got Response from LLM:")
        
    except Exception as e:
        return json.dumps({"error": str(e)})

# Pass query and INP to pre_LLM.py for retrieval
# Query
query="Explain Nationalism in Europe chapter."

# print("\n\n LLM Respone:", determine_retrieval_method(query))

INP = json.loads(determine_retrieval_method(query)).get("trigger") or "metadata_filtering"
# print(INP)
# print(determine_retrieval_method(query))

if INP in["hybrid_search", "metadaa_filtering"]:
    ret_chunks(query, INP=INP)  

else:

    """ calling Fn that connected to: Important_Question_Generation ("Test_Quiz": true),
        Student_performance_Analysis,
        Student_Progress_Tracking, 
        ====Not implemented yet.===="""
    
    # TOC_Overview retrieval.
    if INP == "TOC_Overview":
        TOC_Overview=TOC_Overview(query)  # Code to generate overview of TOC is in retriever_second.py file and saves in docs/Final_LLM_responses/TOC_Overview_from_LLM.txt.
        
    

    


